# Generated by Django 5.1.2 on 2024-11-01 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoim', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='gasto_combustible_por_km',
            new_name='km_por_galon',
        ),
    ]
