# Generated by Django 5.1.1 on 2024-11-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoim', '0004_proyecto_descripcion_corta'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos/'),
        ),
    ]
